---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Start Sever"
  command: mkdir ~/node_server/

- name: "move page file"
  become: yes
  copy:
    src: ../files/index.js
    dest: ~/node_server/

- name: Executing node
  shell: |
    pm2 start ~/node_server/index.js -f